### ISSUE TITLE
可能有数据库连接未关闭的问题

### ISSUE THREAD

**Issue by moxuandeng** [slyak/spring-data-jpa-extra#2]
jpa-extra:  1.2.0.RELEASE

```
<sql name="findByParams">
        <![CDATA[
          SELECT * FROM user WHERE 1 = 1
          <#if username?? && username != ''>
            AND username = :username
          </#if>
        ]]>
    </sql>
```
使用如上方法查询几次后, 会造成如下的错误, 可能是有地方连接未释放

```
org.springframework.orm.jpa.JpaSystemException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:333)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:491)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.slyak.spring.jpa.GenericJpaRepositoryFactory$AssmblerInterceptor.invoke(GenericJpaRepositoryFactory.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy130.findByParams(Unknown Source)
	at com.company.hello.service.UserService.pageQuery(UserService.java:36)
```

**Comment by stormning** [comment]
最近比较忙，过一阵子验证下。不过我用了很久了，没发现这个问题啊

**Comment by moxuandeng** [comment]
连接池用的Druid

分页查询的时候, 很容易就出现了.
```
Page<User> findByParams(Map map, Pageable pageable);
```

在我这属于必现了

**Comment by stormning** [comment]
能把你的配置文件发一下吗，我验证下

**Comment by stormning** [comment]
@moxuandeng 这个问题并不是这个扩展本身的问题
如果你用的spring-boot，那么请设置spring.jpa.open-in-view=true
如果不是，请配置org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter

**Comment by moxuandeng** [comment]
测试了一下, 确实就是这个问题, 多谢解答.

抱歉最近忙其他的事情没有及时补充这个问题.

**Comment by stormning** [comment]
You're welcome ; )
